In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

### 1. Iris-dataset (scikit-learn)

In [3]:
from sklearn.datasets import load_iris
iris_data = load_iris()
iris_data_data = iris_data["data"]
iris_data_target = iris_data["target"]
iris_data_target_names = iris_data["target_names"]
iris_data_feature_names = iris_data["feature_names"]

In [18]:
print(iris_data_data[:3])
print(iris_data_data.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
(150, 4)


In [19]:
print(iris_data_target[:3])
print(iris_data_target.shape)

[0 0 0]
(150,)


In [68]:
type(iris_data_target)

numpy.ndarray

In [14]:
iris_data_target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
iris_data_feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [24]:
iris_df = pd.DataFrame(data=iris_data_data, columns=iris_data_feature_names)

In [67]:
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [62]:
from sklearn.datasets import load_boston
boston_data = load_boston()
boston_data_data = boston_data["data"]
boston_data_target = boston_data["target"]

In [63]:
boston_data_data.shape

(506, 13)

In [66]:
boston_data_data[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [64]:
boston_data_target.shape

(506,)